/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


declare global {
  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }
}



import {
  FancyTabs as FancyTabs
} from './components/fancy-tabs/fancy-tabs';

declare global {
  interface HTMLFancyTabsElement extends FancyTabs, HTMLStencilElement {
  }
  var HTMLFancyTabsElement: {
    prototype: HTMLFancyTabsElement;
    new (): HTMLFancyTabsElement;
  };
  interface HTMLElementTagNameMap {
    "fancy-tabs": HTMLFancyTabsElement;
  }
  interface ElementTagNameMap {
    "fancy-tabs": HTMLFancyTabsElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "fancy-tabs": JSXElements.FancyTabsAttributes;
    }
  }
  namespace JSXElements {
    export interface FancyTabsAttributes extends HTMLAttributes {
      
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
